DROP DATABASE IF EXISTS dezonnevallei;
CREATE DATABASE dezonnevallei;
USE dezonnevallei;

CREATE USER 'hoteladmin'@'localhost' IDENTIFIED BY 'securepass'; 
GRANT ALL PRIVILEGES ON dezonnevallei.* TO 'hoteladmin'@'localhost'; 
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    pass VARCHAR(255) NOT NULL,
    is_admin TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `kamers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `titel` VARCHAR(255) NOT NULL,
  `beschrijving` TEXT NOT NULL,
  'type' VARCHAR(255) NOT NULL,
  `prijs` DECIMAL(10, 2) NOT NULL,
  `afbeelding` VARCHAR(255) NULL
);